# Generated by Django 5.2.7 on 2025-10-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_city_studentprofile_course_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfo',
            name='education_program_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
